#!/usr/bin/env python3
"""Builds the BackOffice "Качи поръчки" page (Import) for the Appsmith git export.

Asked for by Ico on 2026-09-30 for TheBasket.bg: their shop runs on Seliton, which has no
webhook and no plugin we can install, but it can export its orders to Excel. So the
merchant uploads that file here and the portal creates the orders.

**How it works.** The file never leaves the browser as a file. The BoImport widget reads
it (SheetJS for .xlsx/.xls, our own reader for .csv), finds the columns by their names -
all of that is `import-parse.js`, inlined below and tested on its own with Node - and
shows every order as an editable row. "Създай" then creates the chosen ones ONE AT A TIME
through `POST int/v1/portal/orders`, the very endpoint the "Нова поръчка" form uses, so an
imported order is geocoded, priced, quoted and COD-split exactly like a typed one, and is
owned by whoever is logged in (the server takes the merchant from the token).

**The same file uploaded twice** is expected - a shop exports "today's orders" more than
once a day. The shop's order number goes in as `order_source_id`, and since 2026-09-30
the endpoint answers 409 `duplicate` for a number this merchant already has; the row
then says "вече е създадена" instead of sending a driver to the same door twice. That
guard is a backend change (PortalOrderController::create) and must be deployed first.

Output goes to OUT; rsync applies it, exactly like the sibling generators.
"""
import json, os, uuid

import bo_i18n

import os as _os, tempfile as _tempfile

HERE = _os.path.dirname(_os.path.abspath(__file__))
S = HERE
BUILD = _os.path.join(_tempfile.gettempdir(), 'fulfilya-bo-build')
REPO = '/Users/fulfilyaood/Documents/fulfilya/fulfilya-app/pages'
OUT = _os.path.join(BUILD, 'import', 'pages')
APP = '68600ba97c31ed49d151bad2'
PAGE = 'Import'

# pull the shared pieces out of the Табло generator without running its writes (the same
# trick as bo-build-payouts.py)
src = open(f'{S}/bo-build.py', encoding='utf-8').read().split('# ---------------------------------------------------------------- existing widgets, restyled')[0]
src = src.replace("OUT = ", "OUT_UNUSED = ").replace("for n, s in (('BoStats'", "for n, s in (('__skip__'")
ns = {'OUT': _os.path.join(BUILD, 'scratch', 'pages'), '__file__': _os.path.join(HERE, 'bo-build.py')}
exec(compile(src.replace("w('Dashboard/jsobjects/BoNav/BoNav.js', BONAV)", "").replace("w('Dashboard/jsobjects/BoNav/metadata.json'", "(lambda *a, **k: None)('x'"), 'bo-build', 'exec'), ns)
HEADER_HTML, HEADER_CSS, HEADER_JS, TOKENS, FONT_LINK = (ns[k] for k in ('HEADER_HTML', 'HEADER_CSS', 'HEADER_JS', 'TOKENS', 'FONT_LINK'))

PARSER = open(os.path.join(HERE, 'import-parse.js'), encoding='utf-8').read()


def gid(name='x'):
    # Reuse the id the repo already has: a re-minted one comes back as a second copy on Pull.
    for rel in (f'{name}/metadata.json', f'{name.split("/")[0]}/queries/{name.split("/")[-1]}/metadata.json', f'{name.split("/")[0]}/jsobjects/{name.split("/")[-1]}/metadata.json'):
        p = os.path.join(REPO, rel)
        if os.path.exists(p):
            try: return json.load(open(p, encoding='utf-8'))['gitSyncId']
            except Exception: pass
    return f'{APP}_{uuid.uuid5(uuid.NAMESPACE_URL, "fulfilya-backoffice/" + name)}'


def w(path, content):
    p = os.path.join(OUT, path); os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w', encoding='utf-8') as f:
        f.write(content if isinstance(content, str) else json.dumps(content, ensure_ascii=False, indent=2) + '\n')


# ---------------------------------------------------------------- the one REST call
# The body is whatever the widget built for that row (import-parse.js bodyFor()), passed
# in as a run() parameter. It lives in the .txt as well as the metadata: Appsmith reads an
# API body from the .txt and ignores the metadata copy (found 2026-09-16).
BODY = "{{this.params.order}}"
w(f'{PAGE}/queries/ImportOrder/ImportOrder.txt', BODY)
w(f'{PAGE}/queries/ImportOrder/metadata.json', {
    "gitSyncId": gid(f"{PAGE}/ImportOrder"), "id": f"{PAGE}_ImportOrder", "pluginId": "restapi-plugin", "pluginType": "API",
    "unpublishedAction": {
        "actionConfiguration": {
            "autoGeneratedHeaders": [{"key": "content-type", "value": "application/json"}],
            "body": BODY, "bodyFormData": [], "encodeParamsToggle": True,
            "formData": {"apiContentType": "application/json"},
            # The merchant's OWN token: the server resolves who owns the order from it.
            # Accept: application/json or a 422 comes back as a 302 -> 405.
            "headers": [
                {"key": "Authorization", "value": "Bearer {{appsmith.store.authToken}}"},
                {"key": "Accept", "value": "application/json"},
            ],
            "httpMethod": "POST", "httpVersion": "HTTP11", "paginationType": "NONE",
            "path": "/int/v1/portal/orders", "pluginSpecifiedTemplates": [{"value": True}],
            "queryParameters": [],
            # Each order is geocoded and priced server-side before it answers.
            "timeoutInMillisecond": 30000,
        },
        "confirmBeforeExecute": False,
        "datasource": {"datasourceConfiguration": {"url": "https://api.operations.fulfilya.com"},
                       "isAutoGenerated": False, "name": "DEFAULT_REST_DATASOURCE", "pluginId": "restapi-plugin"},
        "dynamicBindingPathList": [{"key": "body"}, {"key": "headers[0].value"}],
        "name": "ImportOrder", "pageId": PAGE, "runBehaviour": "MANUAL", "userSetOnLoad": False}})

# ---------------------------------------------------------------- JS objects
# ImportJS runs the rows one after another and reports each answer through the store,
# which the widget's model reads - so the merchant watches the list fill in. One at a
# time on purpose: every order geocodes against Google and writes a quote, and a burst
# of thirty in parallel is how a rate limit turns into half an import.
IMPORTJS = """export default {
  async createAll(orders, batch) {
    const list = Array.isArray(orders) ? orders : [];
    const items = {};
    const put = (running) => storeValue('imp_results', { batch: batch, items: Object.assign({}, items), running: running, total: list.length });
    await put(true);
    for (const o of list) {
      try {
        const r = await ImportOrder.run({ order: o.body });
        items[o.key] = { ok: true, order_id: (r && r.order_id) || '' };
      } catch (e) {
        // A refused order is an answer, not a crash: the server's reason is in .data.
        const b = ImportOrder.data || {};
        items[o.key] = b.duplicate
          ? { dup: true, order_id: b.order_id || '' }
          : { error: String(b.error || (e && e.message) || '') };
      }
      await put(true);
    }
    await put(false);
    return items;
  }
}
"""

AUTH = open(os.path.join(REPO, 'Reporting/jsobjects/AuthManager/AuthManager.js'), encoding='utf-8').read()
GUARD = open(os.path.join(REPO, 'Reporting/jsobjects/PageGuard/PageGuard.js'), encoding='utf-8').read()


def jsobject(name, body, functions):
    """A JS object plus one query entry per function - Appsmith needs both, and a function
    with no entry is simply not there after a Pull (found 2026-09-17)."""
    w(f'{PAGE}/jsobjects/{name}/{name}.js', body)
    w(f'{PAGE}/jsobjects/{name}/metadata.json', {
        "gitSyncId": gid(f"{PAGE}/{name}"), "id": f"{PAGE}_{name}",
        "unpublishedCollection": {"name": name, "pageId": PAGE, "pluginId": "js-plugin", "pluginType": "JS", "variables": []}})
    for fn, on_load, args in functions:
        w(f'{PAGE}/queries/{name}-{fn}/metadata.json', {
            "gitSyncId": gid(f"{PAGE}/{name}-{fn}"), "id": f"{PAGE}_{name}.{fn}", "pluginId": "js-plugin", "pluginType": "JS",
            "unpublishedAction": {
                "actionConfiguration": {"encodeParamsToggle": True, "isAsync": fn == 'createAll',
                                        "jsArguments": [{"name": a} for a in args], "paginationType": "NONE",
                                        # a whole file of orders at up to 30 s each
                                        "timeoutInMillisecond": 3600000 if fn == 'createAll' else 10000},
                "collectionId": f"{PAGE}_{name}", "confirmBeforeExecute": False,
                "datasource": {"isAutoGenerated": False, "name": "UNUSED_DATASOURCE", "pluginId": "js-plugin"},
                "dynamicBindingPathList": [{"key": "body"}],
                "fullyQualifiedName": f"{name}.{fn}", "name": fn, "pageId": PAGE,
                "runBehaviour": "ON_PAGE_LOAD" if on_load else "MANUAL", "userSetOnLoad": on_load}})


jsobject('AuthManager', AUTH, [('isAuthenticated', False, []), ('login', False, []), ('logout', False, [])])
jsobject('PageGuard', GUARD, [('protectPage', True, [])])
jsobject('ImportJS', IMPORTJS, [('createAll', False, ['orders', 'batch'])])

# ---------------------------------------------------------------- BoImport widget
# SheetJS from cdnjs: the only way to read .xlsx in the browser, and the page already
# loads its fonts from outside. A .csv is read without it, so a blocked CDN still leaves
# CSV working - the widget says so instead of failing silently.
IMPORT_HTML = FONT_LINK + """
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>
<div id="bo-import"></div>"""

IMPORT_CSS = TOKENS + """
.wrap{display:grid;gap:14px;padding:4px 2px 8px}
.row{display:flex;align-items:end;justify-content:space-between;gap:12px;flex-wrap:wrap}
.row h2{font-size:22px;font-weight:800}
.row .sub{color:var(--muted);margin-top:2px}
.card{background:var(--card);border:1px solid var(--line);border-radius:var(--r);padding:16px 18px;box-shadow:var(--shadow);min-width:0}
.card h3{font-size:13px;font-weight:700;color:var(--muted);text-transform:uppercase;letter-spacing:.06em}
.card .hd{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px;flex-wrap:wrap}
.drop{display:grid;place-items:center;gap:8px;text-align:center;border:2px dashed var(--line-strong);border-radius:var(--r);padding:34px 16px;cursor:pointer;background:var(--ground)}
.drop:hover,.drop.over{border-color:var(--accent);background:var(--accent-soft)}
.drop strong{font-family:var(--display);font-size:17px}
.drop .hint{color:var(--muted);font-size:13px}
.drop input{display:none}
.links{display:flex;gap:16px;flex-wrap:wrap;margin-top:12px;font-size:13px;color:var(--muted)}
.link{border:0;background:none;padding:0;color:var(--accent-ink);font-weight:600;cursor:pointer;text-decoration:underline;text-underline-offset:2px;font:inherit}
.btn{border:1px solid var(--line-strong);background:var(--card);border-radius:999px;padding:9px 16px;font-weight:600;cursor:pointer;color:var(--ink);font:inherit}
.btn:hover{border-color:var(--ink)}
.btn.primary{background:var(--accent);border-color:var(--accent);font-weight:700}
.btn.primary:hover{background:var(--accent-hover)}
.btn:disabled{opacity:.5;cursor:default}
.btn:focus-visible,.link:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid var(--accent-ink);outline-offset:2px}
.chips{display:flex;gap:6px;flex-wrap:wrap}
.chip{border-radius:999px;padding:3px 10px;font-size:12px;font-weight:600;background:var(--info-soft);color:var(--muted)}
.chip.ok{background:var(--ok-soft);color:var(--ok)}
.chip.warn{background:var(--warn-soft);color:var(--warn)}
.chip.bad{background:var(--bad-soft);color:var(--bad)}
.notice{border-radius:var(--r-s);padding:10px 14px;background:var(--warn-soft);color:var(--warn);font-size:13px}
.notice.bad{background:var(--bad-soft);color:var(--bad)}
.notice.ok{background:var(--ok-soft);color:var(--ok)}
.tablewrap{overflow-x:auto}
table{border-collapse:collapse;width:100%;min-width:980px}
th{text-align:left;font-size:11px;font-weight:700;color:var(--faint);text-transform:uppercase;letter-spacing:.05em;padding:8px 6px;border-bottom:1px solid var(--line)}
td{padding:6px;border-bottom:1px solid var(--ground);vertical-align:top}
tr.off td{opacity:.55}
tr.bad td{background:#FFF8F7}
td input[type=checkbox]{width:16px;height:16px;margin-top:8px;accent-color:#8A6500;cursor:pointer}
td input:not([type=checkbox]),td select{width:100%;border:1px solid var(--line);border-radius:8px;padding:6px 8px;font:inherit;font-size:13px;background:var(--card);color:var(--ink)}
td input.amt{text-align:right;width:84px}
td select[data-f=payment]{min-width:158px}
td select[data-f=tier]{min-width:124px}
td .no{font-weight:700;white-space:nowrap}
td .items{color:var(--faint);font-size:12px;margin-top:3px}
td .st{font-size:12px;font-weight:600;line-height:1.35}
td .st.ok{color:var(--ok)}
td .st.warn{color:var(--warn)}
td .st.bad{color:var(--bad)}
td .st.muted{color:var(--faint)}
.foot{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-top:12px}
.foot .note{color:var(--faint);font-size:12px;max-width:640px}
"""

IMPORT_JS = PARSER + r"""
// ---------------------------------------------------------------- the widget
const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const plural = (n, one, many) => `${n} ${Number(n) === 1 ? one : many}`;

let state = { file: '', orders: [], notices: [], error: '', batch: '', done: {} };

const NOTICE = {
  'no-header': ['bad', 'Не открихме колони с поръчки в този файл. Проверете дали първият ред съдържа заглавия (Получател, Телефон, Адрес, Сума…) или използвайте примерния файл.'],
  'no-ours': ['', 'В колоната за доставка никъде не пише „Фулфилия“, затова са избрани всички поръчки. Махнете отметката на тези, които не са за нас.'],
  'no-payment': ['', 'Файлът няма колона за плащане. Всички поръчки са маркирани с наложен платеж. Сменете където е нужно.'],
  'no-order-number': ['', 'Файлът няма номер на поръчка. Ако качите същия файл отново, поръчките ще бъдат създадени втори път.'],
  'total-from-items': ['', 'Файлът няма колона с обща сума. Сумата е сметната от цените на продуктите, без доставката. Проверете я.'],
  'no-total': ['', 'Файлът няма колона със сума. Попълнете сумата за наложения платеж на ръка.'],
};

// The server's reasons are written in English for every caller; the merchant reads Bulgarian.
function serverReason(s) {
  const t = String(s || '').toLowerCase();
  if (t.includes('delivery address')) return 'Адресът не беше намерен. Проверете го и опитайте отново.';
  if (t.includes('delivery price') || t.includes('service rate')) return 'Няма зададена цена за доставка. Свържете се с офиса на Фулфилия.';
  if (t.includes('pickup warehouse')) return 'Адресът ви за взимане не е настроен. Свържете се с офиса на Фулфилия.';
  if (t.includes('not linked to a merchant')) return 'Този вход не е свързан с магазин.';
  if (t.includes('phone')) return 'Телефонът не е приет. Проверете го.';
  if (t.includes('email')) return 'Имейлът не е приет. Проверете го или го изтрийте.';
  if (t.includes('timeout') || t.includes('timed out')) return 'Сървърът не отговори навреме. Опитайте отново.';
  return 'Поръчката не беше създадена. ' + (s ? '(' + s + ')' : '');
}

function readFile(f) {
  if (!f) return;
  state = { file: f.name, orders: [], notices: [], error: '', batch: '', done: {} };
  const ext = String(f.name.split('.').pop() || '').toLowerCase();
  const reader = new FileReader();
  reader.onload = () => {
    try {
      const buf = new Uint8Array(reader.result);
      let rows;
      if (ext === 'csv' || ext === 'txt') {
        // Excel in Bulgarian saves CSV as Windows-1251; anything else is UTF-8.
        let text;
        try { text = new TextDecoder('utf-8', { fatal: true }).decode(buf); } catch (e) { text = new TextDecoder('windows-1251').decode(buf); }
        rows = parseCsv(text);
      } else {
        if (typeof XLSX === 'undefined') throw new Error('xlsx-missing');
        const wb = XLSX.read(buf, { type: 'array' });
        rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1, raw: false, defval: '' });
      }
      const r = parseRows(rows);
      state.orders = r.orders;
      state.notices = r.notices;
      if (!r.orders.length && !r.notices.includes('no-header')) state.error = 'Файлът е празен.';
    } catch (e) {
      state.error = e && e.message === 'xlsx-missing'
        ? 'Excel файлът не може да бъде прочетен в момента. Запазете го като CSV и го качете отново.'
        : 'Файлът не може да бъде прочетен. Качете .xlsx, .xls или .csv.';
    }
    render();
  };
  reader.onerror = () => { state.error = 'Файлът не може да бъде прочетен.'; render(); };
  reader.readAsArrayBuffer(f);
}

// Answers from ImportJS arrive through the model; keep every one, across runs, so a row
// created on the first press is never sent again on the second.
function absorb(m) {
  const r = m.results;
  if (!r || !r.batch || !state.batch || r.batch !== state.batch) return null;
  Object.assign(state.done, r.items || {});
  return r;
}

function statusCell(o) {
  const d = state.done[o.key];
  if (d && d.ok) return `<div class="st ok">✓ Създадена</div>`;
  if (d && d.dup) return `<div class="st ok">Вече е създадена</div>`;
  const p = problems(o);
  if (d && d.error) return `<div class="st bad">${esc(serverReason(d.error))}</div>`;
  if (p.length) return `<div class="st bad">${p.map(esc).join('<br>')}</div>`;
  if (o.otherCourier) return `<div class="st muted">Друг куриер</div>`;
  if (o.outsideSofia) return `<div class="st warn">Извън София?</div>`;
  if (!o.include) return `<div class="st muted">Няма да се създаде</div>`;
  return `<div class="st">Готова</div>`;
}

const sent = (o) => { const d = state.done[o.key]; return !!(d && (d.ok || d.dup)); };
const ready = (o) => o.include && !sent(o) && !problems(o).length;

function orderRow(o) {
  const locked = sent(o);
  const p = problems(o);
  const items = (o.items || []).map((it) => `${it.name}${it.quantity > 1 ? ' ×' + it.quantity : ''}`).join(', ');
  const dis = locked ? ' disabled' : '';
  return `<tr class="${!o.include && !locked ? 'off' : ''}${p.length && o.include && !locked ? ' bad' : ''}">` +
    `<td><input type="checkbox" data-k="${o.key}" data-f="include"${o.include || locked ? ' checked' : ''}${dis} aria-label="Създай"></td>` +
    `<td><div class="no">${esc(o.no || '—')}</div></td>` +
    `<td><input data-k="${o.key}" data-f="recipient" value="${esc(o.recipient)}"${dis}>${items ? `<div class="items">${esc(items)}</div>` : ''}</td>` +
    `<td><input data-k="${o.key}" data-f="phone" value="${esc(o.phone)}"${dis}></td>` +
    `<td style="min-width:260px"><input data-k="${o.key}" data-f="address" value="${esc(o.address)}"${dis}></td>` +
    `<td><input class="amt" data-k="${o.key}" data-f="amount" value="${esc(o.amount)}"${dis}></td>` +
    `<td><select data-k="${o.key}" data-f="payment"${dis}><option value="COD"${o.payment === 'COD' ? ' selected' : ''}>Наложен платеж</option><option value="CARD"${o.payment !== 'COD' ? ' selected' : ''}>Платена</option></select></td>` +
    `<td><select data-k="${o.key}" data-f="tier"${dis}><option value="Standard"${o.tier !== 'Express' ? ' selected' : ''}>Стандартна</option><option value="Express"${o.tier === 'Express' ? ' selected' : ''}>Експресна</option></select></td>` +
    `<td style="min-width:150px">${statusCell(o)}</td></tr>`;
}

function render() {
  const m = appsmith.model || {};
  document.documentElement.dataset.theme = 'light';
  const INK = '#1D1D1F';
  document.body.style.color = INK;
  const run = absorb(m);
  const running = !!(run && run.running);

  const intro = `<div class="row"><div><h2 style="color:${INK}">Качи поръчки</h2>` +
    `<div class="sub">от Excel или CSV файл, например експорт от вашия онлайн магазин</div></div></div>`;

  const drop = `<div class="card"><label class="drop" id="drop">` +
    `<input type="file" id="file" accept=".xlsx,.xls,.csv">` +
    `<strong>${state.file ? 'Изберете друг файл' : 'Изберете файл'}</strong>` +
    `<span class="hint">${state.file ? esc(state.file) : '.xlsx, .xls или .csv, или го пуснете тук'}</span></label>` +
    `<div class="links"><button type="button" class="link" data-act="template">Свали примерен файл</button>` +
    `<span>Всеки ред е една поръчка. Задължителни са получател, телефон и адрес, а за наложен платеж и сума.</span></div></div>`;

  let body = '';
  if (state.error) body += `<div class="notice bad">${esc(state.error)}</div>`;
  state.notices.forEach((k) => { const n = NOTICE[k]; if (n) body += `<div class="notice ${n[0]}">${n[1]}</div>`; });

  if (state.orders.length) {
    const toSend = state.orders.filter(ready);
    const created = state.orders.filter((o) => { const d = state.done[o.key]; return d && d.ok; }).length;
    const dups = state.orders.filter((o) => { const d = state.done[o.key]; return d && d.dup; }).length;
    const failed = state.orders.filter((o) => { const d = state.done[o.key]; return d && d.error; }).length;
    const withProblems = state.orders.filter((o) => o.include && !sent(o) && problems(o).length).length;
    const skipped = state.orders.filter((o) => !o.include && !sent(o)).length;

    const chips = `<div class="chips">` +
      `<span class="chip">${plural(state.orders.length, 'поръчка във файла', 'поръчки във файла')}</span>` +
      (toSend.length ? `<span class="chip ok">${plural(toSend.length, 'готова', 'готови')}</span>` : '') +
      (withProblems ? `<span class="chip bad">${plural(withProblems, 'за поправка', 'за поправка')}</span>` : '') +
      (skipped ? `<span class="chip">${plural(skipped, 'пропусната', 'пропуснати')}</span>` : '') +
      `</div>`;

    let progress = '';
    if (running) {
      const n = Object.keys((run && run.items) || {}).length;
      progress = `<div class="notice">Създаване… ${n} от ${run.total}</div>`;
    } else if (created || dups || failed) {
      progress = `<div class="notice ${failed ? 'bad' : 'ok'}">` +
        [created ? plural(created, 'поръчка е създадена', 'поръчки са създадени') : '',
         dups ? plural(dups, 'вече беше създадена', 'вече бяха създадени') + ' по-рано' : '',
         failed ? plural(failed, 'не беше създадена', 'не бяха създадени') + '. Поправете ги и натиснете „Създай“ отново' : '']
          .filter(Boolean).map((t) => `<span>${t}</span>`).join(' · ') + `</div>`;
    }

    body += `<div class="card"><div class="hd"><h3>Поръчки</h3>${chips}</div>` +
      `<div class="tablewrap"><table><thead><tr><th></th><th>№</th><th>Получател</th><th>Телефон</th><th>Адрес</th>` +
      `<th>Сума €</th><th>Плащане</th><th>Доставка</th><th>Статус</th></tr></thead><tbody>` +
      state.orders.map(orderRow).join('') + `</tbody></table></div>` +
      progress +
      `<div class="foot"><span class="note">Сумата е това, което куриерът събира от получателя при наложен платеж. ` +
      `При „Платена“ не се събират пари.</span>` +
      `<span style="display:flex;gap:8px;flex-wrap:wrap">` +
      (created || dups ? `<button type="button" class="btn" data-act="orders">Към поръчките</button>` : '') +
      `<button type="button" class="btn primary" data-act="create"${running || !toSend.length ? ' disabled' : ''}>` +
      `${running ? 'Създаване…' : toSend.length ? 'Създай ' + plural(toSend.length, 'поръчка', 'поръчки') : 'Няма поръчки за създаване'}</button></span></div></div>`;
  }

  document.getElementById('bo-import').innerHTML = `<div class="wrap">${intro}${drop}${body}</div>`;
  wire(running);
}

function wire(running) {
  const input = document.getElementById('file');
  const drop = document.getElementById('drop');
  input.addEventListener('change', () => readFile(input.files && input.files[0]));
  ['dragenter', 'dragover'].forEach((e) => drop.addEventListener(e, (ev) => { ev.preventDefault(); drop.classList.add('over'); }));
  ['dragleave', 'drop'].forEach((e) => drop.addEventListener(e, (ev) => { ev.preventDefault(); drop.classList.remove('over'); }));
  drop.addEventListener('drop', (ev) => readFile(ev.dataTransfer && ev.dataTransfer.files && ev.dataTransfer.files[0]));

  // Edits land in the order on "change" (leaving the field), not on every keystroke:
  // a redraw per key would take the cursor out of the box being typed in.
  document.querySelectorAll('[data-k][data-f]').forEach((el) => el.addEventListener('change', () => {
    const o = state.orders.find((x) => x.key === el.dataset.k);
    if (!o || sent(o)) return;
    const f = el.dataset.f;
    o[f] = el.type === 'checkbox' ? el.checked : el.value;
    // A fixed row forgets the server's last refusal; the next press is a fresh try.
    if (state.done[o.key] && state.done[o.key].error) delete state.done[o.key];
    render();
  }));

  document.querySelectorAll('[data-act]').forEach((el) => el.addEventListener('click', (ev) => {
    ev.preventDefault();
    const act = el.dataset.act;
    if (act === 'create') {
      if (running) return;
      const list = state.orders.filter(ready);
      if (!list.length) return;
      list.forEach((o) => { if (state.done[o.key]) delete state.done[o.key]; });
      state.batch = 'b' + Date.now();
      appsmith.updateModel({ action: 'create', batch: state.batch, orders: list.map((o) => ({ key: o.key, body: bodyFor(o) })) });
      appsmith.triggerEvent('onAction');
      render();
    } else if (act === 'template') {
      if (typeof XLSX !== 'undefined') {
        const wb = XLSX.utils.book_new();
        const ws = XLSX.utils.aoa_to_sheet(TEMPLATE);
        ws['!cols'] = TEMPLATE[0].map((h) => ({ wch: Math.max(12, h.length + 4) }));
        XLSX.utils.book_append_sheet(wb, ws, 'Поръчки');
        const b64 = XLSX.write(wb, { type: 'base64', bookType: 'xlsx' });
        appsmith.updateModel({ action: 'template', data: 'data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,' + b64, filename: 'fulfilya-poruchki.xlsx', mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      } else {
        const csv = '﻿' + TEMPLATE.map((r) => r.map((c) => /[;"\n]/.test(c) ? '"' + c.replace(/"/g, '""') + '"' : c).join(';')).join('\r\n');
        appsmith.updateModel({ action: 'template', data: csv, filename: 'fulfilya-poruchki.csv', mime: 'text/csv' });
      }
      appsmith.triggerEvent('onAction');
    } else if (act === 'orders') {
      appsmith.updateModel({ action: 'orders' });
      appsmith.triggerEvent('onAction');
    }
  }));
}

appsmith.onReady(render);
appsmith.onModelChange(render);
"""

IMP_ON = ("{{(async () => { const m = BoImport.model || {}; "
          "if (m.action === 'create' && Array.isArray(m.orders)) { return ImportJS.createAll(m.orders, m.batch); } "
          "if (m.action === 'template' && m.data) { return download(m.data, m.filename || 'fulfilya-poruchki.xlsx', m.mime || ''); } "
          "if (m.action === 'orders') { return navigateTo('Dashboard', { tab: 'orders' }); } })()}}")

IMP_HEADER_ON = "{{(async () => { const m = BoHeader.model || {}; if (m.action === 'lang') { return storeValue('bo_lang', m.lang || 'bg'); } if (m.action === 'logout') { return AuthManager.logout(); } if (m.action === 'new') { return navigateTo('Dashboard', { new: '1' }); } if (m.action === 'nav') { if (m.tab === 'orders') { return navigateTo('Dashboard', { tab: 'orders' }); } if (m.page) { return navigateTo(m.page); } } })()}}"


def custom(name, top, bottom, html, css, js, model, key_seed, handler, height='FIXED'):
    js = js + bo_i18n.translator_js() + ns['BO_WATCH']
    model = model.replace('{{ { ', '{{ { ' + bo_i18n.MODEL_LANG + ', ', 1)
    w(f'{PAGE}/widgets/{name}.json', {
        "animateLoading": True, "backgroundColor": "transparent", "borderColor": "transparent", "borderRadius": "0px", "borderWidth": "0",
        "boxShadow": "none", "bottomRow": bottom, "defaultModel": model,
        "dynamicBindingPathList": [{"key": "theme"}, {"key": "defaultModel"}],
        "dynamicHeight": height, "dynamicTriggerPathList": [{"key": "onAction"}],
        "events": ["onAction"], "onAction": handler,
        "isLoading": False, "isVisible": True, "key": key_seed, "leftColumn": 0,
        "maxDynamicHeight": 9000, "minDynamicHeight": 4, "minWidth": 450,
        "mobileBottomRow": bottom, "mobileLeftColumn": 0, "mobileRightColumn": 64, "mobileTopRow": top,
        "needsErrorInfo": False, "originalBottomRow": bottom, "originalTopRow": top,
        "parentColumnSpace": 10.484375, "parentId": "0", "parentRowSpace": 10, "renderMode": "CANVAS",
        "responsiveBehavior": "fill", "rightColumn": 64,
        "srcDoc": {"html": html, "css": css, "js": js}, "uncompiledSrcDoc": {"html": html, "css": css, "js": js},
        "theme": "{{appsmith.theme}}", "topRow": top, "type": "CUSTOM_WIDGET", "version": 1,
        "widgetId": "bo" + key_seed[:8], "widgetName": name})


custom('BoHeader', 0, 8, HEADER_HTML, HEADER_CSS, HEADER_JS,
       "{{ { page: 'import', merchant: appsmith.store.customer_name || '' } }}",
       "hdrimport1", IMP_HEADER_ON)
custom('BoImport', 9, 78, IMPORT_HTML, IMPORT_CSS, IMPORT_JS,
       "{{ { results: appsmith.store.imp_results || null } }}",
       "impz8q3w5r", IMP_ON, height='AUTO_HEIGHT')

# ---------------------------------------------------------------- the page itself
w(f'{PAGE}/{PAGE}.json', {
    "gitSyncId": gid(PAGE),
    "unpublishedPage": {
        "isHidden": False,
        "layouts": [{"dsl": {
            "backgroundColor": "none", "bottomRow": 1400, "canExtend": True, "containerStyle": "none",
            "detachFromLayout": True, "dynamicBindingPathList": [], "leftColumn": 0, "minHeight": 560,
            "parentColumnSpace": 1, "parentRowSpace": 1, "rightColumn": 1224, "snapColumns": 64,
            "snapRows": 54, "topRow": 0, "type": "CANVAS_WIDGET", "version": 94,
            "widgetId": "0", "widgetName": "MainContainer"}}],
        "name": PAGE, "slug": "import"}})

print('built into', OUT)
for root, _, files in os.walk(OUT):
    for f in sorted(files): print('  ', os.path.relpath(os.path.join(root, f), OUT))
